# This file generates the GitHub Actions matrix.

board:
  - nice_nano_v2

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle
  - settings_reset

format:
  - bt
  - dongle
  - reset

keymap:
  - charybdis

include:
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: charybdis
    snippet: studio-rpc-usb-uart
